// <auto-generated />
using System;
using CarrinhoCompras.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarrinhoCompras.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CarrinhoComprasDbContext))]
    [Migration("20260916182544_ReservaDeEstoque")]
    partial class ReservaDeEstoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarrinhoCompras.Domain.Carrinhos.Carrinho", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CupomId")
                        .HasColumnType("integer")
                        .HasColumnName("CupomID");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset?>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CupomId");

                    b.ToTable("Carrinho", null, t =>
                        {
                            t.HasCheckConstraint("CK_Carrinho_Status", "\"Status\" IN ('Aberto', 'Finalizado', 'Expirado')");

                            t.HasCheckConstraint("CK_Carrinho_Valores", "\"Subtotal\" >= 0 AND \"Desconto\" >= 0 AND \"Desconto\" <= \"Subtotal\" AND \"Total\" = \"Subtotal\" - \"Desconto\"");
                        });
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Carrinhos.ItemCarrinho", b =>
                {
                    b.Property<Guid>("CarrinhoId")
                        .HasColumnType("uuid")
                        .HasColumnName("CarrinhoID");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer")
                        .HasColumnName("ProdutoID");

                    b.Property<decimal>("PrecoItem")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.HasKey("CarrinhoId", "ProdutoId")
                        .HasName("PK_ItemCarrinho");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ItemCarrinho", null, t =>
                        {
                            t.HasCheckConstraint("CK_ItemCarrinho_PrecoItem", "\"PrecoItem\" = \"PrecoUnitario\" * \"Quantidade\"");

                            t.HasCheckConstraint("CK_ItemCarrinho_Quantidade", "\"Quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Cupons.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.Property<string>("CodigoCupom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PercentualDesconto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCupom")
                        .IsUnique();

                    b.ToTable("Cupom", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cupom_PercentualDesconto", "\"PercentualDesconto\" > 0 AND \"PercentualDesconto\" <= 100");
                        });
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Produtos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("ID");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("PrecoLiquido")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("QuantidadeEstoque")
                        .HasColumnType("integer");

                    b.Property<int>("QuantidadeReservada")
                        .HasColumnType("integer");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("Produto", null, t =>
                        {
                            t.HasCheckConstraint("CK_Produto_PrecoLiquido", "\"PrecoLiquido\" >= 0");

                            t.HasCheckConstraint("CK_Produto_QuantidadeEstoque", "\"QuantidadeEstoque\" >= 0");

                            t.HasCheckConstraint("CK_Produto_QuantidadeReservada", "\"QuantidadeReservada\" >= 0 AND \"QuantidadeReservada\" <= \"QuantidadeEstoque\"");
                        });
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Carrinhos.Carrinho", b =>
                {
                    b.HasOne("CarrinhoCompras.Domain.Cupons.Cupom", "Cupom")
                        .WithMany()
                        .HasForeignKey("CupomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cupom");
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Carrinhos.ItemCarrinho", b =>
                {
                    b.HasOne("CarrinhoCompras.Domain.Carrinhos.Carrinho", null)
                        .WithMany("Itens")
                        .HasForeignKey("CarrinhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarrinhoCompras.Domain.Produtos.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CarrinhoCompras.Domain.Carrinhos.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
